# -*- coding: utf-8 -*-
"""aihealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120B42iutZfudzTUKx30S9JT9u18ktVch
"""

!pip install transformers accelerate gradio

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import gradio as gr

# Load the IBM Granite model from Hugging Face
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM

model_name = "ibm-granite/granite-3.3-2b-instruct"
hf_token = "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"

# Use `token=` instead of `use_auth_token=`
tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token)
model = AutoModelForCausalLM.from_pretrained(model_name, token=hf_token, device_map="auto", trust_remote_code=True)

generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

# Create pipeline
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

# Function 1: Predict Disease from Symptoms
def predict_disease(symptoms):
    prompt = f"""You are a medical AI assistant. A user has the following symptoms: {symptoms}.
Suggest the most likely disease."""
    result = generator(prompt, max_new_tokens=100)[0]['generated_text']
    return result.split(prompt)[-1].strip()

# Function 2: Suggest Natural Remedy from Disease
def suggest_remedy(disease):
    prompt = f"""You are a health assistant. Suggest a natural home remedy for the disease: {disease}."""
    result = generator(prompt, max_new_tokens=100)[0]['generated_text']
    return result.split(prompt)[-1].strip()

# Gradio UI
with gr.Blocks() as demo:
    gr.Markdown("# 🏥 HealthAI - Generative AI Healthcare Assistant")

    with gr.Tab("1️⃣ Symptoms Identifier"):
        symptom_input = gr.Textbox(label="Enter your symptoms (comma-separated)")
        disease_output = gr.Textbox(label="Predicted Disease")
        btn1 = gr.Button("Predict Disease")
        btn1.click(predict_disease, symptom_input, disease_output)

    with gr.Tab("2️⃣ Home Remedies"):
        disease_input = gr.Textbox(label="Enter your disease")
        remedy_output = gr.Textbox(label="Suggested Natural Remedy")
        btn2 = gr.Button("Get Remedy")
        btn2.click(suggest_remedy, disease_input, remedy_output)

demo.launch()